/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MarketSymbol } from '../types';

export const POPULAR_SYMBOLS: MarketSymbol[] = [
  // Crypto - Major Pairs (BTC/ETH/BNB/SOL)
  { symbol: 'BTC/USDT', name: 'Bitcoin', category: 'Crypto', marketStart: '2017-08-17' },
  { symbol: 'ETH/USDT', name: 'Ethereum', category: 'Crypto', marketStart: '2017-08-17' },
  { symbol: 'SOL/USDT', name: 'Solana', category: 'Crypto', marketStart: '2020-04-10' },
  { symbol: 'BNB/USDT', name: 'BNB', category: 'Crypto', marketStart: '2017-11-06' },
  { symbol: 'XRP/USDT', name: 'XRP', category: 'Crypto', marketStart: '2018-05-04' },
  { symbol: 'ADA/USDT', name: 'Cardano', category: 'Crypto', marketStart: '2018-04-17' },
  { symbol: 'DOGE/USDT', name: 'Dogecoin', category: 'Crypto', marketStart: '2019-07-05' },
  { symbol: 'DOT/USDT', name: 'Polkadot', category: 'Crypto', marketStart: '2020-08-18' },
  { symbol: 'MATIC/USDT', name: 'Polygon', category: 'Crypto', marketStart: '2019-04-26' },
  { symbol: 'SHIB/USDT', name: 'Shiba Inu', category: 'Crypto', marketStart: '2021-05-10' },
  { symbol: 'AVAX/USDT', name: 'Avalanche', category: 'Crypto', marketStart: '2020-09-22' },
  { symbol: 'TRX/USDT', name: 'TRON', category: 'Crypto', marketStart: '2018-06-11' },
  { symbol: 'UNI/USDT', name: 'Uniswap', category: 'Crypto', marketStart: '2020-09-17' },
  { symbol: 'LINK/USDT', name: 'Chainlink', category: 'Crypto', marketStart: '2019-01-16' },
  { symbol: 'LTC/USDT', name: 'Litecoin', category: 'Crypto', marketStart: '2017-12-13' },
  { symbol: 'BCH/USDT', name: 'Bitcoin Cash', category: 'Crypto', marketStart: '2017-11-28' },
  { symbol: 'NEAR/USDT', name: 'NEAR Protocol', category: 'Crypto', marketStart: '2020-10-14' },
  { symbol: 'APT/USDT', name: 'Aptos', category: 'Crypto', marketStart: '2022-10-19' },
  { symbol: 'ARB/USDT', name: 'Arbitrum', category: 'Crypto', marketStart: '2023-03-23' },
  { symbol: 'OP/USDT', name: 'Optimism', category: 'Crypto', marketStart: '2022-05-31' },
  { symbol: 'SUI/USDT', name: 'Sui', category: 'Crypto', marketStart: '2023-05-03' },
  { symbol: 'PEPE/USDT', name: 'Pepe', category: 'Crypto', marketStart: '2023-05-05' },
  { symbol: 'FET/USDT', name: 'Fetch.ai', category: 'Crypto', marketStart: '2019-02-28' },
  { symbol: 'RNDR/USDT', name: 'Render', category: 'Crypto', marketStart: '2021-11-27' },
  { symbol: 'STX/USDT', name: 'Stacks', category: 'Crypto', marketStart: '2019-10-24' },
  { symbol: 'FIL/USDT', name: 'Filecoin', category: 'Crypto', marketStart: '2020-10-15' },
  { symbol: 'ICP/USDT', name: 'Internet Computer', category: 'Crypto', marketStart: '2021-05-10' },
  { symbol: 'HBAR/USDT', name: 'Hedera', category: 'Crypto', marketStart: '2019-09-17' },
  { symbol: 'VET/USDT', name: 'VeChain', category: 'Crypto', marketStart: '2018-08-03' },
  { symbol: 'ATOM/USDT', name: 'Cosmos', category: 'Crypto', marketStart: '2019-04-29' },
  { symbol: 'INJ/USDT', name: 'Injective', category: 'Crypto', marketStart: '2020-10-21' },
  { symbol: 'GRT/USDT', name: 'The Graph', category: 'Crypto', marketStart: '2020-12-17' },
  { symbol: 'LDO/USDT', name: 'Lido DAO', category: 'Crypto', marketStart: '2021-05-10' },
  { symbol: 'TIA/USDT', name: 'Celestia', category: 'Crypto', marketStart: '2023-10-31' },
  { symbol: 'KAS/USDT', name: 'Kaspa', category: 'Crypto', marketStart: '2023-11-16' },
  { symbol: 'SEI/USDT', name: 'Sei', category: 'Crypto', marketStart: '2023-08-15' },
  { symbol: 'BONK/USDT', name: 'Bonk', category: 'Crypto', marketStart: '2023-12-22' },
  { symbol: 'FLOKI/USDT', name: 'Floki', category: 'Crypto', marketStart: '2023-05-05' },
  { symbol: 'WIF/USDT', name: 'dogwifhat', category: 'Crypto', marketStart: '2024-03-05' },
  { symbol: 'JUP/USDT', name: 'Jupiter', category: 'Crypto', marketStart: '2024-01-31' },
  { symbol: 'ENA/USDT', name: 'Ethena', category: 'Crypto', marketStart: '2024-04-02' },
  { symbol: 'ORDI/USDT', name: 'ORDI', category: 'Crypto', marketStart: '2023-11-07' },
  { symbol: 'IMX/USDT', name: 'Immutable', category: 'Crypto', marketStart: '2022-01-10' },
  { symbol: 'PYTH/USDT', name: 'Pyth Network', category: 'Crypto', marketStart: '2023-11-20' },

  // User Provided Pairs (BUSD/USDC/USDT variations)
  { symbol: 'AAVE/BUSD', name: 'Aave', category: 'Crypto', marketStart: '2020-10-15' },
  { symbol: 'AAVE/USDC', name: 'Aave', category: 'Crypto', marketStart: '2020-10-15' },
  { symbol: 'AAVE/USDT', name: 'Aave', category: 'Crypto', marketStart: '2020-10-15' },
  { symbol: 'ADA/BUSD', name: 'Cardano', category: 'Crypto', marketStart: '2018-04-17' },
  { symbol: 'ADA/USDC', name: 'Cardano', category: 'Crypto', marketStart: '2018-04-17' },
  { symbol: 'ALGO/BUSD', name: 'Algorand', category: 'Crypto', marketStart: '2019-06-21' },
  { symbol: 'ALGO/USDC', name: 'Algorand', category: 'Crypto', marketStart: '2019-06-21' },
  { symbol: 'ALGO/USDT', name: 'Algorand', category: 'Crypto', marketStart: '2019-06-21' },
  { symbol: 'APT/BUSD', name: 'Aptos', category: 'Crypto', marketStart: '2022-10-19' },
  { symbol: 'APT/USDC', name: 'Aptos', category: 'Crypto', marketStart: '2022-10-19' },
  { symbol: 'ARB/BUSD', name: 'Arbitrum', category: 'Crypto', marketStart: '2023-03-23' },
  { symbol: 'ARB/USDC', name: 'Arbitrum', category: 'Crypto', marketStart: '2023-03-23' },
  { symbol: 'ATOM/BUSD', name: 'Cosmos', category: 'Crypto', marketStart: '2019-04-29' },
  { symbol: 'ATOM/USDC', name: 'Cosmos', category: 'Crypto', marketStart: '2019-04-29' },
  { symbol: 'AVAX/BUSD', name: 'Avalanche', category: 'Crypto', marketStart: '2020-09-22' },
  { symbol: 'AVAX/USDC', name: 'Avalanche', category: 'Crypto', marketStart: '2020-09-22' },
  { symbol: 'BNB/BUSD', name: 'BNB', category: 'Crypto', marketStart: '2017-11-06' },
  { symbol: 'BNB/USDC', name: 'BNB', category: 'Crypto', marketStart: '2017-11-06' },
  { symbol: 'BTC/BUSD', name: 'Bitcoin', category: 'Crypto', marketStart: '2017-08-17' },
  { symbol: 'BTC/USDC', name: 'Bitcoin', category: 'Crypto', marketStart: '2017-08-17' },
  { symbol: 'CAKE/BUSD', name: 'PancakeSwap', category: 'Crypto', marketStart: '2020-09-29' },
  { symbol: 'CAKE/USDC', name: 'PancakeSwap', category: 'Crypto', marketStart: '2020-09-29' },
  { symbol: 'CAKE/USDT', name: 'PancakeSwap', category: 'Crypto', marketStart: '2020-09-29' },
  { symbol: 'COMP/BUSD', name: 'Compound', category: 'Crypto', marketStart: '2020-06-18' },
  { symbol: 'COMP/USDC', name: 'Compound', category: 'Crypto', marketStart: '2020-06-18' },
  { symbol: 'COMP/USDT', name: 'Compound', category: 'Crypto', marketStart: '2020-06-18' },
  { symbol: 'CRV/BUSD', name: 'Curve', category: 'Crypto', marketStart: '2020-08-14' },
  { symbol: 'CRV/USDC', name: 'Curve', category: 'Crypto', marketStart: '2020-08-14' },
  { symbol: 'CRV/USDT', name: 'Curve', category: 'Crypto', marketStart: '2020-08-14' },
  { symbol: 'DASH/BUSD', name: 'Dash', category: 'Crypto', marketStart: '2017-11-01' },
  { symbol: 'DASH/USDC', name: 'Dash', category: 'Crypto', marketStart: '2017-11-01' },
  { symbol: 'DASH/USDT', name: 'Dash', category: 'Crypto', marketStart: '2017-11-01' },
  { symbol: 'DOGE/BUSD', name: 'Dogecoin', category: 'Crypto', marketStart: '2019-07-05' },
  { symbol: 'DOGE/USDC', name: 'Dogecoin', category: 'Crypto', marketStart: '2019-07-05' },
  { symbol: 'DOT/BUSD', name: 'Polkadot', category: 'Crypto', marketStart: '2020-08-18' },
  { symbol: 'DOT/USDC', name: 'Polkadot', category: 'Crypto', marketStart: '2020-08-18' },
  { symbol: 'DYDX/BUSD', name: 'dYdX', category: 'Crypto', marketStart: '2021-09-09' },
  { symbol: 'DYDX/USDC', name: 'dYdX', category: 'Crypto', marketStart: '2021-09-09' },
  { symbol: 'DYDX/USDT', name: 'dYdX', category: 'Crypto', marketStart: '2021-09-09' },
  { symbol: 'EGLD/BUSD', name: 'MultiversX', category: 'Crypto', marketStart: '2020-09-03' },
  { symbol: 'EGLD/USDC', name: 'MultiversX', category: 'Crypto', marketStart: '2020-09-03' },
  { symbol: 'EGLD/USDT', name: 'MultiversX', category: 'Crypto', marketStart: '2020-09-03' },
  { symbol: 'EOS/BUSD', name: 'EOS', category: 'Crypto', marketStart: '2018-05-28' },
  { symbol: 'EOS/USDC', name: 'EOS', category: 'Crypto', marketStart: '2018-05-28' },
  { symbol: 'EOS/USDT', name: 'EOS', category: 'Crypto', marketStart: '2018-05-28' },
  { symbol: 'ETC/BUSD', name: 'Ethereum Classic', category: 'Crypto', marketStart: '2017-11-01' },
  { symbol: 'ETC/USDC', name: 'Ethereum Classic', category: 'Crypto', marketStart: '2017-11-01' },
  { symbol: 'ETC/USDT', name: 'Ethereum Classic', category: 'Crypto', marketStart: '2017-11-01' },
  { symbol: 'ETH/BUSD', name: 'Ethereum', category: 'Crypto', marketStart: '2017-08-17' },
  { symbol: 'ETH/USDC', name: 'Ethereum', category: 'Crypto', marketStart: '2017-08-17' },
  { symbol: 'FIL/BUSD', name: 'Filecoin', category: 'Crypto', marketStart: '2020-10-15' },
  { symbol: 'FIL/USDC', name: 'Filecoin', category: 'Crypto', marketStart: '2020-10-15' },
  { symbol: 'FLOW/BUSD', name: 'Flow', category: 'Crypto', marketStart: '2021-02-15' },
  { symbol: 'FLOW/USDC', name: 'Flow', category: 'Crypto', marketStart: '2021-02-15' },
  { symbol: 'FLOW/USDT', name: 'Flow', category: 'Crypto', marketStart: '2021-02-15' },
  { symbol: 'FTM/BUSD', name: 'Fantom', category: 'Crypto', marketStart: '2019-06-11' },
  { symbol: 'FTM/USDC', name: 'Fantom', category: 'Crypto', marketStart: '2019-06-11' },
  { symbol: 'FTM/USDT', name: 'Fantom', category: 'Crypto', marketStart: '2019-06-11' },
  { symbol: 'GALA/BUSD', name: 'Gala', category: 'Crypto', marketStart: '2020-09-18' },
  { symbol: 'GALA/USDC', name: 'Gala', category: 'Crypto', marketStart: '2020-09-18' },
  { symbol: 'GMX/BUSD', name: 'GMX', category: 'Crypto', marketStart: '2022-10-05' },
  { symbol: 'GMX/USDC', name: 'GMX', category: 'Crypto', marketStart: '2022-10-05' },
  { symbol: 'GMX/USDT', name: 'GMX', category: 'Crypto', marketStart: '2022-10-05' },
  { symbol: 'ICP/BUSD', name: 'Internet Computer', category: 'Crypto', marketStart: '2021-05-10' },
  { symbol: 'ICP/USDC', name: 'Internet Computer', category: 'Crypto', marketStart: '2021-05-10' },
  { symbol: 'INJ/BUSD', name: 'Injective', category: 'Crypto', marketStart: '2020-10-21' },
  { symbol: 'INJ/USDC', name: 'Injective', category: 'Crypto', marketStart: '2020-10-21' },
  { symbol: 'KAVA/BUSD', name: 'Kava', category: 'Crypto', marketStart: '2019-11-22' },
  { symbol: 'KAVA/USDC', name: 'Kava', category: 'Crypto', marketStart: '2019-11-22' },
  { symbol: 'KAVA/USDT', name: 'Kava', category: 'Crypto', marketStart: '2019-11-22' },
  { symbol: 'KSM/BUSD', name: 'Kusama', category: 'Crypto', marketStart: '2020-05-10' },
  { symbol: 'KSM/USDC', name: 'Kusama', category: 'Crypto', marketStart: '2020-05-10' },
  { symbol: 'KSM/USDT', name: 'Kusama', category: 'Crypto', marketStart: '2020-05-10' },
  { symbol: 'LDO/BUSD', name: 'Lido DAO', category: 'Crypto', marketStart: '2021-05-10' },
  { symbol: 'LDO/USDC', name: 'Lido DAO', category: 'Crypto', marketStart: '2021-05-10' },
  { symbol: 'LINK/BUSD', name: 'Chainlink', category: 'Crypto', marketStart: '2019-01-16' },
  { symbol: 'LINK/USDC', name: 'Chainlink', category: 'Crypto', marketStart: '2019-01-16' },
  { symbol: 'LTC/BUSD', name: 'Litecoin', category: 'Crypto', marketStart: '2017-12-13' },
  { symbol: 'LTC/USDC', name: 'Litecoin', category: 'Crypto', marketStart: '2017-12-13' },
  { symbol: 'MANA/BUSD', name: 'Decentraland', category: 'Crypto', marketStart: '2019-02-15' },
  { symbol: 'MANA/USDC', name: 'Decentraland', category: 'Crypto', marketStart: '2019-02-15' },
  { symbol: 'MATIC/BUSD', name: 'Polygon', category: 'Crypto', marketStart: '2019-04-26' },
  { symbol: 'MATIC/USDC', name: 'Polygon', category: 'Crypto', marketStart: '2019-04-26' },
  { symbol: 'NEAR/BUSD', name: 'NEAR Protocol', category: 'Crypto', marketStart: '2020-10-14' },
  { symbol: 'NEAR/USDC', name: 'NEAR Protocol', category: 'Crypto', marketStart: '2020-10-14' },

  { symbol: 'NEO/BUSD', name: 'Neo', category: 'Crypto', marketStart: '2017-11-20' },
  { symbol: 'NEO/USDC', name: 'Neo', category: 'Crypto', marketStart: '2017-11-20' },
  { symbol: 'NEO/USDT', name: 'Neo', category: 'Crypto', marketStart: '2017-11-20' },
  { symbol: 'OP/BUSD', name: 'Optimism', category: 'Crypto', marketStart: '2022-05-31' },
  { symbol: 'OP/USDC', name: 'Optimism', category: 'Crypto', marketStart: '2022-05-31' },
  { symbol: 'RUNE/BUSD', name: 'THORChain', category: 'Crypto', marketStart: '2020-08-18' },
  { symbol: 'RUNE/USDC', name: 'THORChain', category: 'Crypto', marketStart: '2020-08-18' },
  { symbol: 'RUNE/USDT', name: 'THORChain', category: 'Crypto', marketStart: '2020-08-18' },
  { symbol: 'SAND/BUSD', name: 'The Sandbox', category: 'Crypto', marketStart: '2020-08-14' },
  { symbol: 'SAND/USDC', name: 'The Sandbox', category: 'Crypto', marketStart: '2020-08-14' },
  { symbol: 'SAND/USDT', name: 'The Sandbox', category: 'Crypto', marketStart: '2020-08-14' },
  { symbol: 'SNX/BUSD', name: 'Synthetix', category: 'Crypto', marketStart: '2019-01-16' },
  { symbol: 'SNX/USDC', name: 'Synthetix', category: 'Crypto', marketStart: '2019-01-16' },
  { symbol: 'SNX/USDT', name: 'Synthetix', category: 'Crypto', marketStart: '2019-01-16' },
  { symbol: 'SOL/BUSD', name: 'Solana', category: 'Crypto', marketStart: '2020-04-10' },
  { symbol: 'SOL/USDC', name: 'Solana', category: 'Crypto', marketStart: '2020-04-10' },
  { symbol: 'THETA/BUSD', name: 'Theta Network', category: 'Crypto', marketStart: '2019-01-17' },
  { symbol: 'THETA/USDC', name: 'Theta Network', category: 'Crypto', marketStart: '2019-01-17' },
  { symbol: 'THETA/USDT', name: 'Theta Network', category: 'Crypto', marketStart: '2019-01-17' },
  { symbol: 'TRX/BUSD', name: 'TRON', category: 'Crypto', marketStart: '2018-06-11' },
  { symbol: 'TRX/USDC', name: 'TRON', category: 'Crypto', marketStart: '2018-06-11' },
  { symbol: 'UNI/BUSD', name: 'Uniswap', category: 'Crypto', marketStart: '2020-09-17' },
  { symbol: 'UNI/USDC', name: 'Uniswap', category: 'Crypto', marketStart: '2020-09-17' },
  { symbol: 'VET/BUSD', name: 'VeChain', category: 'Crypto', marketStart: '2018-08-03' },
  { symbol: 'VET/USDC', name: 'VeChain', category: 'Crypto', marketStart: '2018-08-03' },
  { symbol: 'XLM/BUSD', name: 'Stellar', category: 'Crypto', marketStart: '2018-08-03' },
  { symbol: 'XLM/USDC', name: 'Stellar', category: 'Crypto', marketStart: '2018-08-03' },
  { symbol: 'XLM/USDT', name: 'Stellar', category: 'Crypto', marketStart: '2018-08-03' },
  { symbol: 'XRP/BUSD', name: 'XRP', category: 'Crypto', marketStart: '2018-05-04' },
  { symbol: 'XRP/USDC', name: 'XRP', category: 'Crypto', marketStart: '2018-05-04' },
  { symbol: 'XTZ/BUSD', name: 'Tezos', category: 'Crypto', marketStart: '2019-09-24' },
  { symbol: 'XTZ/USDC', name: 'Tezos', category: 'Crypto', marketStart: '2019-09-24' },
  { symbol: 'XTZ/USDT', name: 'Tezos', category: 'Crypto', marketStart: '2019-09-24' },
  { symbol: 'ZEC/BUSD', name: 'Zcash', category: 'Crypto', marketStart: '2019-03-11' },
  { symbol: 'ZEC/USDC', name: 'Zcash', category: 'Crypto', marketStart: '2019-03-11' },
  { symbol: 'ZEC/USDT', name: 'Zcash', category: 'Crypto', marketStart: '2019-03-11' },

  // Emerging & Trending
  { symbol: 'W/USDT', name: 'Wormhole', category: 'Crypto', marketStart: '2024-04-03' },
  { symbol: 'REZ/USDT', name: 'Renzo', category: 'Crypto', marketStart: '2024-04-30' },
  { symbol: 'NOT/USDT', name: 'Notcoin', category: 'Crypto', marketStart: '2024-05-16' },
  { symbol: 'BOME/USDT', name: 'BOOK OF MEME', category: 'Crypto', marketStart: '2024-03-14' },
  { symbol: 'BRETT/USDT', name: 'Brett', category: 'Crypto', marketStart: '2024-03-01' },
  { symbol: 'POPCAT/USDT', name: 'Popcat', category: 'Crypto', marketStart: '2024-01-01' },
  { symbol: 'SLERF/USDT', name: 'Slerf', category: 'Crypto', marketStart: '2024-03-18' },
  { symbol: 'DEGEN/USDT', name: 'Degen', category: 'Crypto', marketStart: '2024-01-01' },
  { symbol: 'AERO/USDT', name: 'Aerodrome Finance', category: 'Crypto', marketStart: '2023-08-28' },
  { symbol: 'VELO/USDT', name: 'Velodrome Finance', category: 'Crypto', marketStart: '2022-06-01' },
  { symbol: 'ONDO/USDT', name: 'Ondo', category: 'Crypto', marketStart: '2024-01-18' },
  { symbol: 'PENDLE/USDT', name: 'Pendle', category: 'Crypto', marketStart: '2021-04-28' },
  { symbol: 'AKASH/USDT', name: 'Akash Network', category: 'Crypto', marketStart: '2020-10-15' },
  { symbol: 'KOK/USDT', name: 'KOK', category: 'Crypto', marketStart: '2020-01-01' },
  { symbol: 'SCRT/USDT', name: 'Secret', category: 'Crypto', marketStart: '2020-09-30' },
  { symbol: 'MANTA/USDT', name: 'Manta Network', category: 'Crypto', marketStart: '2024-01-18' },
  { symbol: 'DYM/USDT', name: 'Dymension', category: 'Crypto', marketStart: '2024-02-06' },
  { symbol: 'ARKM/USDT', name: 'Arkham', category: 'Crypto', marketStart: '2023-07-18' },
  { symbol: 'JTO/USDT', name: 'Jito', category: 'Crypto', marketStart: '2023-12-07' },
  { symbol: 'BLUR/USDT', name: 'Blur', category: 'Crypto', marketStart: '2023-02-14' },
  { symbol: 'MINA/USDT', name: 'Mina', category: 'Crypto', marketStart: '2021-06-01' },
  { symbol: 'ASTR/USDT', name: 'Astar', category: 'Crypto', marketStart: '2022-01-17' },
  { symbol: 'GLMR/USDT', name: 'Moonbeam', category: 'Crypto', marketStart: '2022-01-11' },
  { symbol: 'CHZ/USDT', name: 'Chiliz', category: 'Crypto', marketStart: '2019-09-06' },
  { symbol: 'IOTA/USDT', name: 'IOTA', category: 'Crypto', marketStart: '2017-06-13' },
  { symbol: 'KLAY/USDT', name: 'Klaytn', category: 'Crypto', marketStart: '2020-03-01' },
  { symbol: 'LUNC/USDT', name: 'Terra Luna Classic', category: 'Crypto', marketStart: '2019-07-26' },
  { symbol: 'USTC/USDT', name: 'TerraClassicUSD', category: 'Crypto', marketStart: '2020-11-24' },
  { symbol: 'BTT/USDT', name: 'BitTorrent', category: 'Crypto', marketStart: '2019-01-31' },
  { symbol: 'ZIL/USDT', name: 'Zilliqa', category: 'Crypto', marketStart: '2018-01-25' },
  { symbol: 'GNO/USDT', name: 'Gnosis', category: 'Crypto', marketStart: '2017-05-01' },
  { symbol: '1INCH/USDT', name: '1inch Network', category: 'Crypto', marketStart: '2020-12-25' },
  { symbol: 'ANKR/USDT', name: 'Ankr', category: 'Crypto', marketStart: '2019-03-01' },
  { symbol: 'BAT/USDT', name: 'Basic Attention Token', category: 'Crypto', marketStart: '2017-06-01' },
  { symbol: 'ENJ/USDT', name: 'Enjin Coin', category: 'Crypto', marketStart: '2017-11-01' },
  { symbol: 'GALA/USDT', name: 'Gala', category: 'Crypto', marketStart: '2020-09-18' },
  { symbol: 'HOT/USDT', name: 'Holo', category: 'Crypto', marketStart: '2018-04-29' },
  { symbol: 'JASMY/USDT', name: 'JasmyCoin', category: 'Crypto', marketStart: '2021-02-11' },
  { symbol: 'KNC/USDT', name: 'Kyber Network Crystal', category: 'Crypto', marketStart: '2017-09-24' },
  { symbol: 'LRC/USDT', name: 'Loopring', category: 'Crypto', marketStart: '2017-08-30' },
  { symbol: 'OMG/USDT', name: 'OMG Network', category: 'Crypto', marketStart: '2017-07-14' },
  { symbol: 'ONT/USDT', name: 'Ontology', category: 'Crypto', marketStart: '2018-03-08' },
  { symbol: 'QTUM/USDT', name: 'Qtum', category: 'Crypto', marketStart: '2017-09-13' },
  { symbol: 'RVN/USDT', name: 'Ravencoin', category: 'Crypto', marketStart: '2018-03-10' },
  { symbol: 'SC/USDT', name: 'Siacoin', category: 'Crypto', marketStart: '2017-07-02' },
  { symbol: 'STORJ/USDT', name: 'Storj', category: 'Crypto', marketStart: '2017-08-12' },
  { symbol: 'WAVES/USDT', name: 'Waves', category: 'Crypto', marketStart: '2017-06-01' },
  { symbol: 'XEC/USDT', name: 'eCash', category: 'Crypto', marketStart: '2021-07-01' },
  { symbol: 'ZEN/USDT', name: 'Horizen', category: 'Crypto', marketStart: '2017-05-30' },
  { symbol: 'ZRX/USDT', name: '0x', category: 'Crypto', marketStart: '2017-08-16' },


  // Forex - Majors, Minors, and Exotics
  { symbol: 'EURUSD', name: 'Euro / US Dollar', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'GBPUSD', name: 'British Pound / US Dollar', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'USDJPY', name: 'US Dollar / Japanese Yen', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'AUDUSD', name: 'Australian Dollar / US Dollar', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'USDCHF', name: 'US Dollar / Swiss Franc', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'USDCAD', name: 'US Dollar / Canadian Dollar', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'NZDUSD', name: 'New Zealand Dollar / US Dollar', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'EURGBP', name: 'Euro / British Pound', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'EURJPY', name: 'Euro / Japanese Yen', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'GBPJPY', name: 'British Pound / Japanese Yen', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'AUDJPY', name: 'Australian Dollar / Japanese Yen', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'EURCHF', name: 'Euro / Swiss Franc', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'EURAUD', name: 'Euro / Australian Dollar', category: 'Forex', marketStart: '2000-01-01' },
  { symbol: 'GBPAUD', name: 'British Pound / Australian Dollar', category: 'Forex', marketStart: '2000-01-01' },
  
  // Stocks - US (Mag 7 & Popular)
  { symbol: 'AAPL', name: 'Apple Inc.', category: 'Stocks', marketStart: '1980-12-12' },
  { symbol: 'TSLA', name: 'Tesla, Inc.', category: 'Stocks', marketStart: '2010-06-29' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', category: 'Stocks', marketStart: '1999-01-22' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', category: 'Stocks', marketStart: '1986-03-13' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', category: 'Stocks', marketStart: '2004-08-19' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.', category: 'Stocks', marketStart: '1997-05-15' },
  { symbol: 'META', name: 'Meta Platforms, Inc.', category: 'Stocks', marketStart: '2012-05-18' },
  { symbol: 'PLTR', name: 'Palantir Technologies', category: 'Stocks', marketStart: '2020-09-30' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', category: 'Stocks', marketStart: '1980-01-01' },
  { symbol: 'NFLX', name: 'Netflix, Inc.', category: 'Stocks', marketStart: '2002-05-23' },
  { symbol: 'BABA', name: 'Alibaba Group Holding', category: 'Stocks', marketStart: '2014-09-19' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.', category: 'Stocks', marketStart: '1996-05-09' },
  { symbol: 'V', name: 'Visa Inc.', category: 'Stocks', marketStart: '2008-03-19' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', category: 'Stocks', marketStart: '1980-01-01' },
  { symbol: 'DIS', name: 'The Walt Disney Company', category: 'Stocks', marketStart: '1980-01-01' },
  { symbol: 'PYPL', name: 'PayPal Holdings, Inc.', category: 'Stocks', marketStart: '2015-07-20' },
  { symbol: 'SQ', name: 'Block, Inc.', category: 'Stocks', marketStart: '2015-11-19' },
  { symbol: 'SHOP', name: 'Shopify Inc.', category: 'Stocks', marketStart: '2015-05-21' },
  { symbol: 'COIN', name: 'Coinbase Global, Inc.', category: 'Stocks', marketStart: '2021-04-14' },
  { symbol: 'MSTR', name: 'MicroStrategy Incorporated', category: 'Stocks', marketStart: '1998-06-11' },
  { symbol: 'MARA', name: 'Marathon Digital Holdings', category: 'Stocks', marketStart: '2013-05-01' },
  { symbol: 'RIOT', name: 'Riot Platforms, Inc.', category: 'Stocks', marketStart: '2003-01-01' },
  
  // Stocks - International
  { symbol: 'TM', name: 'Toyota Motor Corp', category: 'Stocks', marketStart: '1980-01-01' },
  { symbol: 'ASML', name: 'ASML Holding N.V.', category: 'Stocks', marketStart: '2000-01-01' },
  { symbol: 'SAP', name: 'SAP SE', category: 'Stocks', marketStart: '2000-01-01' },
  { symbol: 'HSBC', name: 'HSBC Holdings plc', category: 'Stocks', marketStart: '2000-01-01' },
  
  // Indices - Global Benchmarks
  { symbol: 'SPX', name: 'S&P 500 Index', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'IXIC', name: 'Nasdaq Composite', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'DJI', name: 'Dow Jones Industrial Average', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'DXY', name: 'US Dollar Index', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'NI225', name: 'Nikkei 225', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'FTSE', name: 'FTSE 100 Index', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'DAX', name: 'DAX 40 Index', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'CAC', name: 'CAC 40 Index', category: 'Indices', marketStart: '1980-01-01' },
  { symbol: 'HSI', name: 'Hang Seng Index', category: 'Indices', marketStart: '1980-01-01' },

  // Metals - Commodities
  { symbol: 'XAUUSD', name: 'Gold / US Dollar', category: 'Metals', marketStart: '2000-01-01' },
  { symbol: 'XAGUSD', name: 'Silver / US Dollar', category: 'Metals', marketStart: '2000-01-01' },
  { symbol: 'PLATINUM', name: 'Platinum', category: 'Metals', marketStart: '2000-01-01', comingSoon: true },
  { symbol: 'PALLADIUM', name: 'Palladium', category: 'Metals', marketStart: '2000-01-01', comingSoon: true },
  { symbol: 'COPPER', name: 'Copper', category: 'Metals', marketStart: '2000-01-01', comingSoon: true },

  // Others - Energy
  { symbol: 'WTI', name: 'Crude Oil WTI', category: 'Others', marketStart: '2000-01-01' },
  { symbol: 'BRENT', name: 'Crude Oil Brent', category: 'Others', marketStart: '2000-01-01' },
  { symbol: 'NATGAS', name: 'Natural Gas', category: 'Others', marketStart: '2000-01-01' },
];
